### ISSUE TITLE
Missing package.json

### ISSUE THREAD

**Issue by retroflex** [bureus/MMM-Vasttrafik-PublicTransport#1]
Looks like a nice module! Trying to get it running now...

Had to install requred npm packages manually though. Even though installation instructions in the readme said to run npm install. I guess adding a package.json file would fix this.

**Comment by bureus** [comment]
Hi, thanks for comments, pretty new to this, so will look into asap! Thanks for the tip!

**Comment by bureus** [comment]
Resolved in latest commit, thanks for the advice! 👍
