### ISSUE TITLE
Wrong time

### ISSUE THREAD

**Issue by henper** [bureus/MMM-Vasttrafik-PublicTransport#16]
When the current time for depature is before midnight and the next depature is after, the time to next departure time is faulty calculated and gets huge, like it's calculated from next depature, forward, to the current time stamp.

**Comment by bureus** [comment]
Will look into it!

**Comment by bureus** [comment]
So I have found out that there is actually a bug inside västtrafiks API, so will need to reach out to them to get it resolved. Meanwhile i will do an ugly hack to resolve it.

**Comment by bureus** [comment]
@henper after some trials I have been able to hopefully close the bug. So please update to latest version and test and reopen this issue if not resolved.

**Comment by mopsmannen** [comment]
Hi

Looks good after after midnight but the hour before (2300-2359) shows very bizarre departuretimes. 
On these photos time can be seen top left. Two photos are before midnight and the next tram towards Angered was already departed.
![3F6DE5C5-4426-4B61-BD7D-E94BE4EA11FE](https://user-images.githubusercontent.com/76181889/104110415-a84d0c00-52d7-11eb-8860-771a5b9bf987.jpeg)


![EBFA4106-FEA1-4841-BE37-8DB5F9A2B39F](https://user-images.githubusercontent.com/76181889/104110411-a5eab200-52d7-11eb-87f8-886f7f9df5fa.jpeg)
![17B07304-7E7A-412E-8160-47FE600329F3](https://user-images.githubusercontent.com/76181889/104110413-a7b47580-52d7-11eb-9e83-a707e19b6645.jpeg)

**Comment by fillilutten** [comment]
Any news? This problem still exists.
