### ISSUE TITLE
Request: Departure time colors

### ISSUE THREAD

**Issue by fillilutten** [bureus/MMM-Vasttrafik-PublicTransport#17]
I would like to be able to set some colors depending on how close to departure there is. So from 1-4 minutes = set ex red color, but would like to choose exact, from 5-6 = set orange and all above 6 minut set a third color.

**Comment by bureus** [comment]
Great idea, will work on this and include it in the next patch

**Comment by bureus** [comment]
@fillilutten your feature has been implemented, please update the module and read the section **Departure time colors** in readme. Please let me know if there is anything not working or if its not according to requirements.

**Comment by fillilutten** [comment]
Hej,

Jag ville bara be om ursäkt å det grövsta att jag aldrig gav dig respons och ett stort(!) tack för att du gjorde denna förbättring. Jag var tvungen att lägga magicmirror-projektet lite på is och då glömdes detta av att både implementera och även ge dig respons. Hur som så uppskattas det enormt, stort tack återigen.

Bifogar en bild på hur det ser ut på min display här hemma.

https://imgur.com/a/NGXxgUX


Dock på sena kvällar händer något konstigt, såhär visar den upp tiden då, vad kan det bero på?

Vänligen,
Jacob
