### ISSUE TITLE
Missing comma in the config script,

### ISSUE THREAD

**Issue by MiAnger** [bureus/MMM-Vasttrafik-PublicTransport#18]
There is a a comma missing in the config after the showDestinationName:
Probably obvius to you but for me with no programming background it took the better part of the evning to find.

![bild](https://user-images.githubusercontent.com/80063995/110239283-6b536d80-7f46-11eb-8394-b8cf53ab0070.png)

**Comment by bureus** [comment]
Thanks @MiAnger for reporting, I found one more place as well. Resolved an updated now.
