### ISSUE TITLE
wrong colors on tram.

### ISSUE THREAD

**Issue by Rakutsi** [bureus/MMM-Vasttrafik-PublicTransport#19]
![tram](https://user-images.githubusercontent.com/84444162/118787713-60488200-b893-11eb-9e63-f2fd187e81f8.JPG).

I am new on this , but did manage to get the tram stop and so as i wanted.
But the colors of the trams is not the colors like you have in your pictures. Is it somthing that i did or missed doing?

**Comment by Rakutsi** [comment]
did solve it myself by switching place of color and bgColor in MMM-Vasttrafik-PublicTransport.js file.

**Comment by bureus** [comment]
Thanks for report @Rakutsi, resolved now. I guess västtrafik fixed there API as well :)
