### ISSUE TITLE
Some bus names are too wide

### ISSUE THREAD

**Issue by retroflex** [bureus/MMM-Vasttrafik-PublicTransport#2]
Have been using your module for a week now and it's working great! You should post it to the magicmirror forum in case you haven't already.

I have a problem with grön express going outside its designated box:
![image](https://user-images.githubusercontent.com/25268023/46458998-e3d30480-c7b7-11e8-957a-cdb3d4d9d555.png)

Test for example with: stopIds: ['9021014018130000']

Not sure how to best handle it. Maybe I can change custom.css somehow? CSS is not my strong side...

**Comment by bureus** [comment]
Thanks for the bug report, resolved in latest commit so please update :) 

![image](https://user-images.githubusercontent.com/603643/46583179-ce2d3b80-ca52-11e8-911a-a9a02647ba1c.png)

**Comment by retroflex** [comment]
Updated now and it works fine. Great work! Thanks.
