### ISSUE TITLE
Limited departure info

### ISSUE THREAD

**Issue by Zoonie81** [bureus/MMM-Vasttrafik-PublicTransport#28]
@Xkhi thanks for updating and forking this! I'll write this here since you haven't activated "issues" on your fork. I'm seeing some issues compared to the master, not sure why.

* Upcoming departures (after next) column is almost always empty
* Using multiple stops, the second stop only shows 1-2 lines at most

 I've checked API v4 console and the info is there, it just doesn't output properly in this module. Do you have the same issues?

EDIT: I believe any departure longer than 10 min away is lost and not shown. If there is a departure or an upcoming departure after next within 10 min it seems to show up.  all other fall into undefined and is presented with a dash (-) in the time table. This also seems to be the reason the second stop in my list only shows 1-2 lines, since those busses depart with longer intervals.

**Comment by Xkhi** [comment]
Thanks for letting me know, I have enabled issues in my fork, you can close this and move the conversation over there
