### ISSUE TITLE
How do I make font smaller?

### ISSUE THREAD

**Issue by retroflex** [bureus/MMM-Vasttrafik-PublicTransport#4]
I've tried a few things to make the font smaller, but I'm stuck... you seem to be good at css, so maybe you have an idea?

I tried adding this to custom.css:

.departure-board {
	font-size: 70%;
}

But nothing happens. I could of course edit this in board.css, but that would be wrong.

**Comment by bureus** [comment]
Sorry for late reply have been offline in china for 12 days so had not had time to reply before. Hm, i can check what we can do, currently using the Magic Mirrors default CSS. Would you like to be able to fully controll the font size, or will it be ok to be able to select from diffrent themes? Like "Large", "Medium", "Small"? 

What you can do is to change the board.css like this: 
![image](https://user-images.githubusercontent.com/603643/48970447-86677100-f00c-11e8-83f0-fe29ec5e5caf.png)

**Comment by retroflex** [comment]
Thanks! I learned some more about css and found out a way to do this in custom.css, which will work on any module:

```
.MMM-Vasttrafik-PublicTransport .module-content {
	transform-origin: right top;
	transform: scale(0.85, 0.85);
}

```

Top right because that's my position of the module.

**Comment by bureus** [comment]
Great that you found a solution!! 👍 💯  Would you like me to close the ticket?
