### ISSUE TITLE
More config options

### ISSUE THREAD

**Issue by retroflex** [bureus/MMM-Vasttrafik-PublicTransport#5]
It's me again :) Two ideas for additional config options:

1) Show track column (true/false). Often you know where to go, so this could save up some screen space.

2) Show bus stop header (e.g. "Varbergsgatan, Göteborg") (true/false). Makes sense when you have a list with only one bus stop, which is where you are. No need to show it then.

**Comment by bureus** [comment]
Great idea! Will include that in the next release! :)

**Comment by bureus** [comment]
Resolved in latest release, please see section "Configurations" added two new configs, showTrackNumbers and showStopHeader. Set them to false in order to hide columns. Screenshot also added see "Minimal layout".

**Comment by retroflex** [comment]
Great! Although with stop header, this is what I meant:

![image](https://user-images.githubusercontent.com/25268023/49108828-6a243800-f289-11e8-9b2a-7027430970a1.png)

But maybe there's point in hiding the destination column too.... if you travel from an end stop, that might be unnecessary to show.

**Comment by bureus** [comment]
Hi, sorry for the confusion, i have released a feature to hide that header name. Please verify when you have time :)

**Comment by retroflex** [comment]
Works good and the result looks very nice. Thanks for all the work with the module!
