### ISSUE TITLE
Getting error when starting MagicMirror

### ISSUE THREAD

**Issue by EhsanMomeni81** [bureus/MMM-Vasttrafik-PublicTransport#7]
Hi again,

I added this to the config-file

`{
            module: 'MMM-Vasttrafik-PublicTransport',
            position: 'bottom_left',
            header: "Västtrafik",
            config: {
                     stopIds: ["9022014081600023"],   // REQUIRED. An array of stop is's. Your are required to have at least one stop.
                                                   // see 3. Get stops that you want to track.
                     appKey: "bMbAX67XXXXXXXXXXXXXX",       // REQUIRED. see 1. Create application and obtain required client id and secret.
                     appSecret: "LdgSDgfXXXXXXXXXXXXXX", // REQUIRED. see 1. Create application and obtain required client id and secret.
                     debug: false,                 // Optional. Enable some extra output when debugging.
                     sortBy: "track"               // Optional. Sort your departure board by either "track", "direction", "line" or "type"
                                                   // default is "track".
                     refreshRate: "60000"          // Optional. Refresh rate int milliseconds, default is 60 seconds.
                     trafficSituations: true,      // Optional. Default is false, you need a subscription to TrafficSituations v1 API please see Prerequisites 2.1
                     board: {
                        destination: {
                            maxPxWidth: 150       // Optional. Force max width for destination names.
                        }, 
                    },
                    showTrackNumbers: false,     //Optional. Default is true, if set to false will hide track column.
                    showStopHeader: false        //Optional. Default is true, if set to false will hide direction/stop column.   
            }
        },`

But when i launch MM I get: "WARNING! Could not validate config file. Please correct syntax errors. Starting with default configuration."

When I remove the module-code I don't get the warning, and MM launches as usual.

**Comment by bureus** [comment]
Hm... Im not sure, but it feels like it could be something wrong with the json config. Cant get it to validate when running it in VS. So can you please try with this (same config as im currently running). 

`{
            module: 'MMM-Vasttrafik-PublicTransport',
            position: 'bottom_left',
            header: "Västtrafik",
            config: {
                stopIds: ["9022014081600023"],
                appKey: "bMbAX67XXXXXXXXXXXXXX",
                appSecret: "LdgSDgfXXXXXXXXXXXXXX",
                debug: true,
                sortBy: "track",
                refreshRate: "20000",
                trafficSituations: false,
                board: {
                    destination: {
                        maxPxWidth: 200
                    }
                },
                showTrackNumbers: true,
                showStopHeader: true
            }
        },`

**Comment by EhsanMomeni81** [comment]
Thank you,
I don't know what the difference is between your code and mine, and I'm too new at this to spot the difference, but now it works perfectly. Thank you so much.

**Comment by bureus** [comment]
Glad that it worked out! 👍
