### ISSUE TITLE
location ID

### ISSUE THREAD

**Issue by ZachariasHultman** [bureus/MMM-Vasttrafik-PublicTransport#9]
Hi!

I cant find the correct location ID at västrtrafik.

I want to get all departures from Regnbågsgatan and can't get that to work. The module is showing but i get error when running the code.

such as:
generateAccessToken failed =StausCodeError: 401 - "{\"error\":\"invalid_client\",\"error_description\":\"Oauth application is not in active state.\"}".

I have followed all your steps and followed "Reseplaneraren v2".

What can i do now to fix this?

**Comment by bureus** [comment]
Hi @ZachariasHultman ,

401 means that your authorization token is wrong. Seems like something has happen on your application. Can you ensure that your client id and secret is correct and that your application is live? 

You can find your secret and id on developer portal at västtrafik (https://developer.vasttrafik.se/portal/#/applications) 

Here is all ids for Regnbågsgatan: 
<?xml version="1.0" encoding="UTF-8"?>
<LocationList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://api.vasttrafik.se/v1/hafasRestLocation.xsd" servertime="14:35" serverdate="2019-12-15">
<StopLocation name="Regnbågsgatan, Göteborg" lon="11.942754" lat="57.710774" id="9021014005465000" idx="1"/>
<CoordLocation name="Regnbågsgatan, 417 55 Göteborg" lon="11.945019" lat="57.710226" type="ADR" idx="2"/>
<StopLocation name="Regnbågsskolan, Gullspång" lon="14.214984" lat="58.863101" id="9021014030167000" idx="3"/>
<CoordLocation name="Regnbågsvägen, 461 59 Trollhättan" lon="12.279813" lat="58.303343" type="ADR" idx="4"/>
<CoordLocation name="Regnbågsvägen, 438 94 Härryda" lon="12.387486" lat="57.649387" type="ADR" idx="5"/>
<CoordLocation name="Regnbågsvägen, 512 65 Mjöbäck" lon="12.869344" lat="57.312273" type="ADR" idx="6"/>
<CoordLocation name="Regnbågsvägen, 541 33 Skövde" lon="13.820735" lat="58.393586" type="ADR" idx="7"/>
<CoordLocation name="Regnbågsvägen, 441 73 Sollebrunn" lon="12.583352" lat="58.137177" type="ADR" idx="8"/>
<CoordLocation name="Regnbågsvägen, 531 58 Lidköping" lon="13.131119" lat="58.543076" type="ADR" idx="9"/>
<CoordLocation name="Regnbågsvägen Korrastugan, 512 65 Mjöbäck" lon="12.868319" lat="57.313927" type="ADR" idx="10"/>
<StopLocation name="Pilbågsgatan, Göteborg" lon="11.984652" lat="57.684517" id="9021014005280000" idx="11"/>
<CoordLocation name="Pilbågsgatan, 412 59 Göteborg" lon="11.987574" lat="57.684373" type="ADR" idx="12"/>
<CoordLocation name="Pilbågsgatan, 463 30 Lilla Edet" lon="12.132390" lat="58.141330" type="ADR" idx="13"/>
<CoordLocation name="Bågskyttegatan, 431 43 Mölndal" lon="11.999233" lat="57.659787" type="ADR" idx="14"/>
<CoordLocation name="Rymdvågsgatan, 421 33 Västra Frölunda" lon="11.927130" lat="57.652030" type="ADR" idx="15"/>
<CoordLocation name="Bandsågsgatan, 416 79 Göteborg" lon="12.048233" lat="57.713633" type="ADR" idx="16"/>
<CoordLocation name="Järnvågsgatan, 413 27 Göteborg" lon="11.951177" lat="57.700374" type="ADR" idx="17"/>
<CoordLocation name="Klyvsågsgatan, 416 79 Göteborg" lon="12.049024" lat="57.712743" type="ADR" idx="18"/>
<CoordLocation name="Kortvågsgatan, 421 33 Västra Frölunda" lon="11.927823" lat="57.653684" type="ADR" idx="19"/>
<CoordLocation name="Långvågsgatan, 421 33 Västra Frölunda" lon="11.927400" lat="57.652569" type="ADR" idx="20"/>
<CoordLocation name="Markvågsgatan, 421 33 Västra Frölunda" lon="11.927068" lat="57.651481" type="ADR" idx="21"/>
<CoordLocation name="Mellanvågsgatan, 421 33 Västra Frölunda" lon="11.927580" lat="57.653126" type="ADR" idx="22"/>
<CoordLocation name="Snälltågsgatan, 521 32 Falköping" lon="13.554852" lat="58.183715" type="ADR" idx="23"/>
<CoordLocation name="Rågskärsgatan, 456 43 Väjern" lon="11.261812" lat="58.376281" type="ADR" idx="24"/>
<CoordLocation name="Sågställaregatan, 416 79 Göteborg" lon="12.049366" lat="57.713345" type="ADR" idx="25"/>
<CoordLocation name="Regnvädersgatan, 418 32 Göteborg" lon="11.888396" lat="57.714963" type="ADR" idx="26"/>
<StopLocation name="Företagsgatan 44, Borås" lon="12.845064" lat="57.704769" id="9021014082944000" idx="27"/>
<StopLocation name="Företagsgatan 64, Borås" lon="12.843140" lat="57.701938" id="9021014082372000" idx="28"/>
<StopLocation name="Regementsgatan, Borås" lon="12.923072" lat="57.712365" id="9021014082745000" idx="29"/>
<StopLocation name="Regementsgatan, Vänersborg" lon="12.333865" lat="58.378807" id="9021014080065000" idx="30"/>
<StopLocation name="Bergslagsgatan, Åmål" lon="12.701290" lat="59.052576" id="9021014085056000" idx="31"/>
<CoordLocation name="Bågegatan, 534 91 Vara" lon="12.999804" lat="58.254657" type="ADR" idx="32"/>
<CoordLocation name="Bågegatan, 531 52 Lidköping" lon="13.141232" lat="58.501267" type="ADR" idx="33"/>
<CoordLocation name="Regeringsgatan, 544 30 Hjo" lon="14.287437" lat="58.302669" type="ADR" idx="34"/>
<CoordLocation name="Stjärnbåtsgatan, 426 71 Västra Frölunda" lon="11.891093" lat="57.680238" type="ADR" idx="35"/>
<CoordLocation name="Sågspånsgatan, 416 80 Göteborg" lon="12.042363" lat="57.710927" type="ADR" idx="36"/>
<StopLocation name="Beväringsgatan, Göteborg" lon="12.028565" lat="57.739863" id="9021014001450000" idx="37"/>
<CoordLocation name="Gullregnsgatan, 543 32 Tibro" lon="14.158298" lat="58.414944" type="ADR" idx="38"/>
<CoordLocation name="Bagaregårdsgatan, 416 70 Göteborg" lon="12.011395" lat="57.718100" type="ADR" idx="39"/>
<CoordLocation name="Roslagsgatan, 441 57 Alingsås" lon="12.509712" lat="57.947262" type="ADR" idx="40"/>
<CoordLocation name="Rysshagsgatan, 504 94 Borås" lon="12.822501" lat="57.684759" type="ADR" idx="41"/>
<CoordLocation name="Rågångsgatan, 461 40 Trollhättan" lon="12.314610" lat="58.288178" type="ADR" idx="42"/>
<CoordLocation name="Rågångsgatan, 461 42 Trollhättan" lon="12.316795" lat="58.286641" type="ADR" idx="43"/>
<StopLocation name="Ättehögsgatan, Göteborg" lon="12.028448" lat="57.719979" id="9021014007750000" idx="44"/>
<StopLocation name="Varbergsgatan, Göteborg" lon="12.002811" lat="57.680031" id="9021014007270000" idx="45"/>
<StopLocation name="Egnahemsgatan, Borås" lon="12.812739" lat="57.614320" id="9021014082314000" idx="46"/>
<StopLocation name="Grågåsgatan, Mölndal" lon="11.986522" lat="57.677748" id="9021014012261000" idx="47"/>
<StopLocation name="Hållingsgatan, Borås" lon="12.918236" lat="57.716455" id="9021014082055000" idx="48"/>
<StopLocation name="Järnvägsgatan, Borås" lon="12.942813" lat="57.725319" id="9021014082715000" idx="49"/>
<StopLocation name="Skillingsgatan, Borås" lon="12.987192" lat="57.722226" id="9021014082762000" idx="50"/>
</LocationList>

**Comment by bureus** [comment]
`<?xml` version="1.0" encoding="UTF-8"?>
<LocationList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://api.vasttrafik.se/v1/hafasRestLocation.xsd" servertime="14:35" serverdate="2019-12-15">
<StopLocation name="Regnbågsgatan, Göteborg" lon="11.942754" lat="57.710774" id="9021014005465000" idx="1"/>
<CoordLocation name="Regnbågsgatan, 417 55 Göteborg" lon="11.945019" lat="57.710226" type="ADR" idx="2"/>
<StopLocation name="Regnbågsskolan, Gullspång" lon="14.214984" lat="58.863101" id="9021014030167000" idx="3"/>
<CoordLocation name="Regnbågsvägen, 461 59 Trollhättan" lon="12.279813" lat="58.303343" type="ADR" idx="4"/>
<CoordLocation name="Regnbågsvägen, 438 94 Härryda" lon="12.387486" lat="57.649387" type="ADR" idx="5"/>
<CoordLocation name="Regnbågsvägen, 512 65 Mjöbäck" lon="12.869344" lat="57.312273" type="ADR" idx="6"/>
<CoordLocation name="Regnbågsvägen, 541 33 Skövde" lon="13.820735" lat="58.393586" type="ADR" idx="7"/>
<CoordLocation name="Regnbågsvägen, 441 73 Sollebrunn" lon="12.583352" lat="58.137177" type="ADR" idx="8"/>
<CoordLocation name="Regnbågsvägen, 531 58 Lidköping" lon="13.131119" lat="58.543076" type="ADR" idx="9"/>
<CoordLocation name="Regnbågsvägen Korrastugan, 512 65 Mjöbäck" lon="12.868319" lat="57.313927" type="ADR" idx="10"/>
<StopLocation name="Pilbågsgatan, Göteborg" lon="11.984652" lat="57.684517" id="9021014005280000" idx="11"/>
<CoordLocation name="Pilbågsgatan, 412 59 Göteborg" lon="11.987574" lat="57.684373" type="ADR" idx="12"/>
<CoordLocation name="Pilbågsgatan, 463 30 Lilla Edet" lon="12.132390" lat="58.141330" type="ADR" idx="13"/>
<CoordLocation name="Bågskyttegatan, 431 43 Mölndal" lon="11.999233" lat="57.659787" type="ADR" idx="14"/>
<CoordLocation name="Rymdvågsgatan, 421 33 Västra Frölunda" lon="11.927130" lat="57.652030" type="ADR" idx="15"/>
<CoordLocation name="Bandsågsgatan, 416 79 Göteborg" lon="12.048233" lat="57.713633" type="ADR" idx="16"/>
<CoordLocation name="Järnvågsgatan, 413 27 Göteborg" lon="11.951177" lat="57.700374" type="ADR" idx="17"/>
<CoordLocation name="Klyvsågsgatan, 416 79 Göteborg" lon="12.049024" lat="57.712743" type="ADR" idx="18"/>
<CoordLocation name="Kortvågsgatan, 421 33 Västra Frölunda" lon="11.927823" lat="57.653684" type="ADR" idx="19"/>
<CoordLocation name="Långvågsgatan, 421 33 Västra Frölunda" lon="11.927400" lat="57.652569" type="ADR" idx="20"/>
<CoordLocation name="Markvågsgatan, 421 33 Västra Frölunda" lon="11.927068" lat="57.651481" type="ADR" idx="21"/>
<CoordLocation name="Mellanvågsgatan, 421 33 Västra Frölunda" lon="11.927580" lat="57.653126" type="ADR" idx="22"/>
<CoordLocation name="Snälltågsgatan, 521 32 Falköping" lon="13.554852" lat="58.183715" type="ADR" idx="23"/>
<CoordLocation name="Rågskärsgatan, 456 43 Väjern" lon="11.261812" lat="58.376281" type="ADR" idx="24"/>
<CoordLocation name="Sågställaregatan, 416 79 Göteborg" lon="12.049366" lat="57.713345" type="ADR" idx="25"/>
<CoordLocation name="Regnvädersgatan, 418 32 Göteborg" lon="11.888396" lat="57.714963" type="ADR" idx="26"/>
<StopLocation name="Företagsgatan 44, Borås" lon="12.845064" lat="57.704769" id="9021014082944000" idx="27"/>
<StopLocation name="Företagsgatan 64, Borås" lon="12.843140" lat="57.701938" id="9021014082372000" idx="28"/>
<StopLocation name="Regementsgatan, Borås" lon="12.923072" lat="57.712365" id="9021014082745000" idx="29"/>
<StopLocation name="Regementsgatan, Vänersborg" lon="12.333865" lat="58.378807" id="9021014080065000" idx="30"/>
<StopLocation name="Bergslagsgatan, Åmål" lon="12.701290" lat="59.052576" id="9021014085056000" idx="31"/>
<CoordLocation name="Bågegatan, 534 91 Vara" lon="12.999804" lat="58.254657" type="ADR" idx="32"/>
<CoordLocation name="Bågegatan, 531 52 Lidköping" lon="13.141232" lat="58.501267" type="ADR" idx="33"/>
<CoordLocation name="Regeringsgatan, 544 30 Hjo" lon="14.287437" lat="58.302669" type="ADR" idx="34"/>
<CoordLocation name="Stjärnbåtsgatan, 426 71 Västra Frölunda" lon="11.891093" lat="57.680238" type="ADR" idx="35"/>
<CoordLocation name="Sågspånsgatan, 416 80 Göteborg" lon="12.042363" lat="57.710927" type="ADR" idx="36"/>
<StopLocation name="Beväringsgatan, Göteborg" lon="12.028565" lat="57.739863" id="9021014001450000" idx="37"/>
<CoordLocation name="Gullregnsgatan, 543 32 Tibro" lon="14.158298" lat="58.414944" type="ADR" idx="38"/>
<CoordLocation name="Bagaregårdsgatan, 416 70 Göteborg" lon="12.011395" lat="57.718100" type="ADR" idx="39"/>
<CoordLocation name="Roslagsgatan, 441 57 Alingsås" lon="12.509712" lat="57.947262" type="ADR" idx="40"/>
<CoordLocation name="Rysshagsgatan, 504 94 Borås" lon="12.822501" lat="57.684759" type="ADR" idx="41"/>
<CoordLocation name="Rågångsgatan, 461 40 Trollhättan" lon="12.314610" lat="58.288178" type="ADR" idx="42"/>
<CoordLocation name="Rågångsgatan, 461 42 Trollhättan" lon="12.316795" lat="58.286641" type="ADR" idx="43"/>
<StopLocation name="Ättehögsgatan, Göteborg" lon="12.028448" lat="57.719979" id="9021014007750000" idx="44"/>
<StopLocation name="Varbergsgatan, Göteborg" lon="12.002811" lat="57.680031" id="9021014007270000" idx="45"/>
<StopLocation name="Egnahemsgatan, Borås" lon="12.812739" lat="57.614320" id="9021014082314000" idx="46"/>
<StopLocation name="Grågåsgatan, Mölndal" lon="11.986522" lat="57.677748" id="9021014012261000" idx="47"/>
<StopLocation name="Hållingsgatan, Borås" lon="12.918236" lat="57.716455" id="9021014082055000" idx="48"/>
<StopLocation name="Järnvägsgatan, Borås" lon="12.942813" lat="57.725319" id="9021014082715000" idx="49"/>
<StopLocation name="Skillingsgatan, Borås" lon="12.987192" lat="57.722226" id="9021014082762000" idx="50"/>
</LocationList>``

**Comment by bureus** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<LocationList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://api.vasttrafik.se/v1/hafasRestLocation.xsd" servertime="14:35" serverdate="2019-12-15">
<StopLocation name="Regnbågsgatan, Göteborg" lon="11.942754" lat="57.710774" id="9021014005465000" idx="1"/>
<CoordLocation name="Regnbågsgatan, 417 55 Göteborg" lon="11.945019" lat="57.710226" type="ADR" idx="2"/>
<StopLocation name="Regnbågsskolan, Gullspång" lon="14.214984" lat="58.863101" id="9021014030167000" idx="3"/>
<CoordLocation name="Regnbågsvägen, 461 59 Trollhättan" lon="12.279813" lat="58.303343" type="ADR" idx="4"/>
<CoordLocation name="Regnbågsvägen, 438 94 Härryda" lon="12.387486" lat="57.649387" type="ADR" idx="5"/>
<CoordLocation name="Regnbågsvägen, 512 65 Mjöbäck" lon="12.869344" lat="57.312273" type="ADR" idx="6"/>
<CoordLocation name="Regnbågsvägen, 541 33 Skövde" lon="13.820735" lat="58.393586" type="ADR" idx="7"/>
<CoordLocation name="Regnbågsvägen, 441 73 Sollebrunn" lon="12.583352" lat="58.137177" type="ADR" idx="8"/>
<CoordLocation name="Regnbågsvägen, 531 58 Lidköping" lon="13.131119" lat="58.543076" type="ADR" idx="9"/>
<CoordLocation name="Regnbågsvägen Korrastugan, 512 65 Mjöbäck" lon="12.868319" lat="57.313927" type="ADR" idx="10"/>
<StopLocation name="Pilbågsgatan, Göteborg" lon="11.984652" lat="57.684517" id="9021014005280000" idx="11"/>
<CoordLocation name="Pilbågsgatan, 412 59 Göteborg" lon="11.987574" lat="57.684373" type="ADR" idx="12"/>
<CoordLocation name="Pilbågsgatan, 463 30 Lilla Edet" lon="12.132390" lat="58.141330" type="ADR" idx="13"/>
<CoordLocation name="Bågskyttegatan, 431 43 Mölndal" lon="11.999233" lat="57.659787" type="ADR" idx="14"/>
<CoordLocation name="Rymdvågsgatan, 421 33 Västra Frölunda" lon="11.927130" lat="57.652030" type="ADR" idx="15"/>
<CoordLocation name="Bandsågsgatan, 416 79 Göteborg" lon="12.048233" lat="57.713633" type="ADR" idx="16"/>
<CoordLocation name="Järnvågsgatan, 413 27 Göteborg" lon="11.951177" lat="57.700374" type="ADR" idx="17"/>
<CoordLocation name="Klyvsågsgatan, 416 79 Göteborg" lon="12.049024" lat="57.712743" type="ADR" idx="18"/>
<CoordLocation name="Kortvågsgatan, 421 33 Västra Frölunda" lon="11.927823" lat="57.653684" type="ADR" idx="19"/>
<CoordLocation name="Långvågsgatan, 421 33 Västra Frölunda" lon="11.927400" lat="57.652569" type="ADR" idx="20"/>
<CoordLocation name="Markvågsgatan, 421 33 Västra Frölunda" lon="11.927068" lat="57.651481" type="ADR" idx="21"/>
<CoordLocation name="Mellanvågsgatan, 421 33 Västra Frölunda" lon="11.927580" lat="57.653126" type="ADR" idx="22"/>
<CoordLocation name="Snälltågsgatan, 521 32 Falköping" lon="13.554852" lat="58.183715" type="ADR" idx="23"/>
<CoordLocation name="Rågskärsgatan, 456 43 Väjern" lon="11.261812" lat="58.376281" type="ADR" idx="24"/>
<CoordLocation name="Sågställaregatan, 416 79 Göteborg" lon="12.049366" lat="57.713345" type="ADR" idx="25"/>
<CoordLocation name="Regnvädersgatan, 418 32 Göteborg" lon="11.888396" lat="57.714963" type="ADR" idx="26"/>
<StopLocation name="Företagsgatan 44, Borås" lon="12.845064" lat="57.704769" id="9021014082944000" idx="27"/>
<StopLocation name="Företagsgatan 64, Borås" lon="12.843140" lat="57.701938" id="9021014082372000" idx="28"/>
<StopLocation name="Regementsgatan, Borås" lon="12.923072" lat="57.712365" id="9021014082745000" idx="29"/>
<StopLocation name="Regementsgatan, Vänersborg" lon="12.333865" lat="58.378807" id="9021014080065000" idx="30"/>
<StopLocation name="Bergslagsgatan, Åmål" lon="12.701290" lat="59.052576" id="9021014085056000" idx="31"/>
<CoordLocation name="Bågegatan, 534 91 Vara" lon="12.999804" lat="58.254657" type="ADR" idx="32"/>
<CoordLocation name="Bågegatan, 531 52 Lidköping" lon="13.141232" lat="58.501267" type="ADR" idx="33"/>
<CoordLocation name="Regeringsgatan, 544 30 Hjo" lon="14.287437" lat="58.302669" type="ADR" idx="34"/>
<CoordLocation name="Stjärnbåtsgatan, 426 71 Västra Frölunda" lon="11.891093" lat="57.680238" type="ADR" idx="35"/>
<CoordLocation name="Sågspånsgatan, 416 80 Göteborg" lon="12.042363" lat="57.710927" type="ADR" idx="36"/>
<StopLocation name="Beväringsgatan, Göteborg" lon="12.028565" lat="57.739863" id="9021014001450000" idx="37"/>
<CoordLocation name="Gullregnsgatan, 543 32 Tibro" lon="14.158298" lat="58.414944" type="ADR" idx="38"/>
<CoordLocation name="Bagaregårdsgatan, 416 70 Göteborg" lon="12.011395" lat="57.718100" type="ADR" idx="39"/>
<CoordLocation name="Roslagsgatan, 441 57 Alingsås" lon="12.509712" lat="57.947262" type="ADR" idx="40"/>
<CoordLocation name="Rysshagsgatan, 504 94 Borås" lon="12.822501" lat="57.684759" type="ADR" idx="41"/>
<CoordLocation name="Rågångsgatan, 461 40 Trollhättan" lon="12.314610" lat="58.288178" type="ADR" idx="42"/>
<CoordLocation name="Rågångsgatan, 461 42 Trollhättan" lon="12.316795" lat="58.286641" type="ADR" idx="43"/>
<StopLocation name="Ättehögsgatan, Göteborg" lon="12.028448" lat="57.719979" id="9021014007750000" idx="44"/>
<StopLocation name="Varbergsgatan, Göteborg" lon="12.002811" lat="57.680031" id="9021014007270000" idx="45"/>
<StopLocation name="Egnahemsgatan, Borås" lon="12.812739" lat="57.614320" id="9021014082314000" idx="46"/>
<StopLocation name="Grågåsgatan, Mölndal" lon="11.986522" lat="57.677748" id="9021014012261000" idx="47"/>
<StopLocation name="Hållingsgatan, Borås" lon="12.918236" lat="57.716455" id="9021014082055000" idx="48"/>
<StopLocation name="Järnvägsgatan, Borås" lon="12.942813" lat="57.725319" id="9021014082715000" idx="49"/>
<StopLocation name="Skillingsgatan, Borås" lon="12.987192" lat="57.722226" id="9021014082762000" idx="50"/>
</LocationList>

**Comment by bureus** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<LocationList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://api.vasttrafik.se/v1/hafasRestLocation.xsd" servertime="14:35" serverdate="2019-12-15">
<StopLocation name="Regnbågsgatan, Göteborg" lon="11.942754" lat="57.710774" id="9021014005465000" idx="1"/>
<CoordLocation name="Regnbågsgatan, 417 55 Göteborg" lon="11.945019" lat="57.710226" type="ADR" idx="2"/>
<StopLocation name="Regnbågsskolan, Gullspång" lon="14.214984" lat="58.863101" id="9021014030167000" idx="3"/>
<CoordLocation name="Regnbågsvägen, 461 59 Trollhättan" lon="12.279813" lat="58.303343" type="ADR" idx="4"/>
<CoordLocation name="Regnbågsvägen, 438 94 Härryda" lon="12.387486" lat="57.649387" type="ADR" idx="5"/>
<CoordLocation name="Regnbågsvägen, 512 65 Mjöbäck" lon="12.869344" lat="57.312273" type="ADR" idx="6"/>
<CoordLocation name="Regnbågsvägen, 541 33 Skövde" lon="13.820735" lat="58.393586" type="ADR" idx="7"/>
<CoordLocation name="Regnbågsvägen, 441 73 Sollebrunn" lon="12.583352" lat="58.137177" type="ADR" idx="8"/>
<CoordLocation name="Regnbågsvägen, 531 58 Lidköping" lon="13.131119" lat="58.543076" type="ADR" idx="9"/>
<CoordLocation name="Regnbågsvägen Korrastugan, 512 65 Mjöbäck" lon="12.868319" lat="57.313927" type="ADR" idx="10"/>
<StopLocation name="Pilbågsgatan, Göteborg" lon="11.984652" lat="57.684517" id="9021014005280000" idx="11"/>
<CoordLocation name="Pilbågsgatan, 412 59 Göteborg" lon="11.987574" lat="57.684373" type="ADR" idx="12"/>
<CoordLocation name="Pilbågsgatan, 463 30 Lilla Edet" lon="12.132390" lat="58.141330" type="ADR" idx="13"/>
<CoordLocation name="Bågskyttegatan, 431 43 Mölndal" lon="11.999233" lat="57.659787" type="ADR" idx="14"/>
<CoordLocation name="Rymdvågsgatan, 421 33 Västra Frölunda" lon="11.927130" lat="57.652030" type="ADR" idx="15"/>
<CoordLocation name="Bandsågsgatan, 416 79 Göteborg" lon="12.048233" lat="57.713633" type="ADR" idx="16"/>
<CoordLocation name="Järnvågsgatan, 413 27 Göteborg" lon="11.951177" lat="57.700374" type="ADR" idx="17"/>
<CoordLocation name="Klyvsågsgatan, 416 79 Göteborg" lon="12.049024" lat="57.712743" type="ADR" idx="18"/>
<CoordLocation name="Kortvågsgatan, 421 33 Västra Frölunda" lon="11.927823" lat="57.653684" type="ADR" idx="19"/>
<CoordLocation name="Långvågsgatan, 421 33 Västra Frölunda" lon="11.927400" lat="57.652569" type="ADR" idx="20"/>
<CoordLocation name="Markvågsgatan, 421 33 Västra Frölunda" lon="11.927068" lat="57.651481" type="ADR" idx="21"/>
<CoordLocation name="Mellanvågsgatan, 421 33 Västra Frölunda" lon="11.927580" lat="57.653126" type="ADR" idx="22"/>
<CoordLocation name="Snälltågsgatan, 521 32 Falköping" lon="13.554852" lat="58.183715" type="ADR" idx="23"/>
<CoordLocation name="Rågskärsgatan, 456 43 Väjern" lon="11.261812" lat="58.376281" type="ADR" idx="24"/>
<CoordLocation name="Sågställaregatan, 416 79 Göteborg" lon="12.049366" lat="57.713345" type="ADR" idx="25"/>
<CoordLocation name="Regnvädersgatan, 418 32 Göteborg" lon="11.888396" lat="57.714963" type="ADR" idx="26"/>
<StopLocation name="Företagsgatan 44, Borås" lon="12.845064" lat="57.704769" id="9021014082944000" idx="27"/>
<StopLocation name="Företagsgatan 64, Borås" lon="12.843140" lat="57.701938" id="9021014082372000" idx="28"/>
<StopLocation name="Regementsgatan, Borås" lon="12.923072" lat="57.712365" id="9021014082745000" idx="29"/>
<StopLocation name="Regementsgatan, Vänersborg" lon="12.333865" lat="58.378807" id="9021014080065000" idx="30"/>
<StopLocation name="Bergslagsgatan, Åmål" lon="12.701290" lat="59.052576" id="9021014085056000" idx="31"/>
<CoordLocation name="Bågegatan, 534 91 Vara" lon="12.999804" lat="58.254657" type="ADR" idx="32"/>
<CoordLocation name="Bågegatan, 531 52 Lidköping" lon="13.141232" lat="58.501267" type="ADR" idx="33"/>
<CoordLocation name="Regeringsgatan, 544 30 Hjo" lon="14.287437" lat="58.302669" type="ADR" idx="34"/>
<CoordLocation name="Stjärnbåtsgatan, 426 71 Västra Frölunda" lon="11.891093" lat="57.680238" type="ADR" idx="35"/>
<CoordLocation name="Sågspånsgatan, 416 80 Göteborg" lon="12.042363" lat="57.710927" type="ADR" idx="36"/>
<StopLocation name="Beväringsgatan, Göteborg" lon="12.028565" lat="57.739863" id="9021014001450000" idx="37"/>
<CoordLocation name="Gullregnsgatan, 543 32 Tibro" lon="14.158298" lat="58.414944" type="ADR" idx="38"/>
<CoordLocation name="Bagaregårdsgatan, 416 70 Göteborg" lon="12.011395" lat="57.718100" type="ADR" idx="39"/>
<CoordLocation name="Roslagsgatan, 441 57 Alingsås" lon="12.509712" lat="57.947262" type="ADR" idx="40"/>
<CoordLocation name="Rysshagsgatan, 504 94 Borås" lon="12.822501" lat="57.684759" type="ADR" idx="41"/>
<CoordLocation name="Rågångsgatan, 461 40 Trollhättan" lon="12.314610" lat="58.288178" type="ADR" idx="42"/>
<CoordLocation name="Rågångsgatan, 461 42 Trollhättan" lon="12.316795" lat="58.286641" type="ADR" idx="43"/>
<StopLocation name="Ättehögsgatan, Göteborg" lon="12.028448" lat="57.719979" id="9021014007750000" idx="44"/>
<StopLocation name="Varbergsgatan, Göteborg" lon="12.002811" lat="57.680031" id="9021014007270000" idx="45"/>
<StopLocation name="Egnahemsgatan, Borås" lon="12.812739" lat="57.614320" id="9021014082314000" idx="46"/>
<StopLocation name="Grågåsgatan, Mölndal" lon="11.986522" lat="57.677748" id="9021014012261000" idx="47"/>
<StopLocation name="Hållingsgatan, Borås" lon="12.918236" lat="57.716455" id="9021014082055000" idx="48"/>
<StopLocation name="Järnvägsgatan, Borås" lon="12.942813" lat="57.725319" id="9021014082715000" idx="49"/>
<StopLocation name="Skillingsgatan, Borås" lon="12.987192" lat="57.722226" id="9021014082762000" idx="50"/>
</LocationList>`

**Comment by bureus** [comment]
Also please ensure you have a subscription for your application: https://developer.vasttrafik.se/portal/#/subscriptions

**Comment by bureus** [comment]
Can you also please verify that you have an access token visible on: https://developer.vasttrafik.se/portal/#/api/Reseplaneraren/v2/landerss

![image](https://user-images.githubusercontent.com/603643/70863530-80ab3900-1f49-11ea-8088-7633432648ad.png)

**Comment by ZachariasHultman** [comment]
I have an access token visable at Reseplaneraren v2, similar as your picture shows. I think i might have problem with my application. I'm doing this on a raspberry pie and couldn't get "GET https://api.vasttrafik.se/bin/rest.exe/v2/location.name?input=centralstationen HTTP/1.1
Authorization: Bearer [access_token]" to work in the terminal. Maybe it has something to do with that. I have tripple checked my appKey and appSecret and they are correct. 

What more exactily do you meen with that my application is live?

**Comment by bureus** [comment]
Okej, i guess it might be so that you are doing something wrong when converting your client id and secret to authorization header manually. Can you call the location endpoint from developer portal? (see screen below). If that works then you just need to setup apps config. 

In order to run it locally you need to create a basic auth from your client id and secret. Have you followed the steps here? https://developer.vasttrafik.se/portal/#/guides/oauth2.

So what you can do, is to set your config to: 
`{
            module: 'MMM-Vasttrafik-PublicTransport',
            position: 'bottom_left',
            header: "Västtrafik",
            config: {
                stopIds: ["9021014005465000"], //Regnbågsgatan
                appKey: "REPLACEWITHYOURCLIENTID",
                appSecret: "REPLACEWITHYOURCLIENTSECRET",
                debug: false,
                sortBy: "track",
                refreshRate: "20000",
                trafficSituations: false,
                board: {
                    destination: {
                        maxPxWidth: 200
                    }
                }
            }
        }`

![image](https://user-images.githubusercontent.com/603643/70868120-8884d080-1f7d-11ea-814e-3500b5a733eb.png)

**Comment by ZachariasHultman** [comment]
Alright. I proparly have problem with oauth. I cant get "POST" and "GET" to work proparly in the terminal. Will do some more reserach about this. 

thanks for your help

**Comment by bureus** [comment]
No worries good luck :) Will close the issue, please feel free to reopen if you cant solve it.
